name: data

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - postprocess.ts

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          max_attemps : 3
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          max_attemps : 3
      - name: Fetch data
        uses: githubocto/flat@v3.3.1
        with:
          http_url: https://api.btctools.io/api/leaderboard
          downloaded_filename: bitmex-leaderboard.json
          postprocess: postprocess.ts
          max_attemps : 3
